name: PayHome
version: 0.1
main: tw.longcat.lab.PayHome.PayHome
depend: [ Vault, CommandBook ]
commands:
   payhome:
      description: 'Teleport Player to there home with some cost.'
      usage: '/payhome: Pay for teleporting to home.'